# Generated by Django 6.0.6 on 2026-07-01 04:20

import cora.models
import cora.utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cora', '0002_setup_pgmq_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaapplication',
            name='id',
            field=models.CharField(default=cora.utils.ids.generate_uuid7, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='labelimage',
            name='ocr_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='labelimage',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labelimage',
            name='id',
            field=models.CharField(default=cora.utils.ids.generate_uuid7, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labelimage',
            name='image',
            field=models.ImageField(upload_to=cora.models.get_label_upload_path),
        ),
    ]
