# Generated by Django 6.0.6 on 2026-06-26 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cora', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colaapplication',
            name='prior_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='colaapplication',
            name='review_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colaapplication',
            name='review_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colaapplication',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='colaapplication',
            name='date_of_application',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='colaapplication',
            name='product_type',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='colaapplication',
            name='status',
            field=models.CharField(db_index=True, default='RECEIVED', max_length=30),
        ),
    ]
