# Generated by Django 6.0.6 on 2026-06-27 09:15

import cora.utils.ids
from django.db import migrations, models


def gen_uuid7(apps, schema_editor):
    ColaApplication = apps.get_model('cora', 'ColaApplication')
    LabelImage = apps.get_model('cora', 'LabelImage')
    for obj in ColaApplication.objects.all():
        obj.uuid_id = cora.utils.ids.generate_uuid7()
        obj.save(update_fields=['uuid_id'])
    for obj in LabelImage.objects.all():
        obj.uuid_id = cora.utils.ids.generate_uuid7()
        obj.save(update_fields=['uuid_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('cora', '0003_colaapplication_prior_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaapplication',
            name='uuid_id',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='labelimage',
            name='uuid_id',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='labelimage',
            name='uuid_cola_application',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.RunPython(gen_uuid7, reverse_code=migrations.RunPython.noop),
    ]