# Generated by Django 6.0.6 on 2026-07-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cora', '0003_labelimage_ocr_status_labelimage_ocr_text_and_more'),
    ]

    operations = [
    ]
