# Generated by Django 6.0.6 on 2026-06-27 09:20

from django.db import migrations


def migrate_fk(apps, schema_editor):
    ColaApplication = apps.get_model('cora', 'ColaApplication')
    LabelImage = apps.get_model('cora', 'LabelImage')
    # Map old PK -> new UUID
    pk_to_uuid = {str(app.id): app.uuid_id for app in ColaApplication.objects.all()}
    for img in LabelImage.objects.all():
        old_fk = str(img.cola_application_id)
        if old_fk in pk_to_uuid:
            img.uuid_cola_application = pk_to_uuid[old_fk]
            img.save(update_fields=['uuid_cola_application'])


class Migration(migrations.Migration):

    dependencies = [
        ('cora', '0004_add_uuid_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_fk, reverse_code=migrations.RunPython.noop),
    ]