# Generated by Django 6.0.6 on 20 2026-06-27 10:00

import cora.utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cora', '0005_migrate_fk_to_uuid'),
    ]

    operations = [
        # Step 1: Remove old FK constraint
        migrations.RemoveField(
            model_name='labelimage',
            name='cola_application',
        ),
        # Step 2: Remove old primary key fields
        migrations.RemoveField(
            model_name='colaapplication',
            name='id',
        ),
        migrations.RemoveField(
            model_name='labelimage',
            name='id',
        ),
        # Step 3: Rename UUID columns to target names using raw SQL
        migrations.RunSQL(
            sql=[
                'ALTER TABLE cola_applications RENAME COLUMN uuid_id TO id;',
                'ALTER TABLE label_images RENAME COLUMN uuid_id TO id;',
                'ALTER TABLE label_images RENAME COLUMN uuid_cola_application TO cola_application_id;',
            ],
            reverse_sql=[
                'ALTER TABLE cola_applications RENAME COLUMN id TO uuid_id;',
                'ALTER TABLE label_images RENAME COLUMN id TO uuid_id;',
                'ALTER TABLE label_images RENAME COLUMN cola_application_id TO uuid_cola_application;',
            ],
        ),
        # Step 4: Set new 'id' fields as primary keys
        migrations.AlterField(
            model_name='colaapplication',
            name='id',
            field=models.CharField(default=cora.utils.ids.generate_uuid7, max_length=36, primary_key=True),
        ),
        migrations.AlterField(
            model_name='labelimage',
            name='id',
            field=models.CharField(default=cora.utils.ids.generate_uuid7, max_length=36, primary_key=True),
        ),
        # Step 5: Set up the new FK
        migrations.RunPython(
            code=lambda apps, schema_editor: schema_editor.execute(
                'ALTER TABLE label_images ADD CONSTRAINT label_images_cola_application_id_fkey FOREIGN KEY (cola_application_id) REFERENCES cola_applications(id)'
            )
            if getattr(schema_editor.connection, 'vendor', None) != 'sqlite'
            else None,
            reverse_code=lambda apps, schema_editor: schema_editor.execute(
                'ALTER TABLE label_images DROP CONSTRAINT label_images_cola_application_id_fkey'
            )
            if getattr(schema_editor.connection, 'vendor', None) != 'sqlite'
            else None,
        ),
        migrations.AddField(
            model_name='labelimage',
            name='cola_application',
            field=models.ForeignKey(
                db_column='cola_application_id',
                on_delete=models.CASCADE,
                related_name='label_images',
                to='cora.colaapplication',
            ),
        ),
    ]