# Generated by Django 6.0.6 on 2026-07-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cora', '0005_add_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='prefix',
            field=models.CharField(db_index=True, help_text='First 8 chars for lookup', max_length=8),
        ),
    ]
