# Generated by Django 6.0.6 on 2026-07-02 13:01

from django.db import migrations


def create_custom_permissions(apps, schema_editor):
    """Create custom permissions for CORA models."""
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    ColaApplication = apps.get_model('cora', 'ColaApplication')

    ct = ContentType.objects.get_for_model(ColaApplication)

    permissions = [
        ('review_application', 'Can review COLA applications'),
        ('import_application', 'Can import COLA applications'),
    ]

    for codename, name in permissions:
        Permission.objects.get_or_create(
            codename=codename,
            content_type=ct,
            defaults={'name': name}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cora', '0006_extend_apitoken_prefix'),
    ]

    operations = [
        migrations.RunPython(create_custom_permissions, migrations.RunPython.noop),
    ]
