# Generated by Django 6.0.6 on 2026-07-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cora', '0007_add_custom_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='name',
            field=models.CharField(help_text='Human-readable label for the token', max_length=100),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='prefix',
            field=models.CharField(db_index=True, help_text='First 16 chars for token lookup', max_length=16),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='scopes',
            field=models.JSONField(default=list, help_text="List of scopes: ['read'], ['write'], or ['review']"),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='token_hash',
            field=models.CharField(help_text='PBKDF2-SHA256 hash of the full token', max_length=128),
        ),
    ]
